Первая версия ФЗ 6
Mentagia/java-kanban pull request #1
Opened 2024-09-07 15:28 UTC by Mentagia

Добавил реализацию LinkedList в HistoryManager.
Добавил методы в HistoryManager, а также тесты на них.
Добавил реализацию метода удаления из истории в метода TaskManager.
Добавил дополнительный сценарий проверки в Main.

2024-09-09 06:48 UTC, YazykovMikhail requested changes

2024-09-09 06:48 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lyubavin/schedule/manager/InMemoryHistoryManager.java
> +    public void remove(int id) {
Избегай двойных поисков
```
	public void remove(int id) {
		final Node node = history.remove(id);
		if (node == null) {
			return;
		}
		removeNode(node);
	}
```

2024-09-09 06:48 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lyubavin/schedule/manager/InMemoryHistoryManager.java
> +    private final Map<Integer, Node<Task>> historyMap = new HashMap<>();
Просто history 
Не используй типы переменных в названиях

2024-09-09 06:48 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lyubavin/schedule/manager/InMemoryHistoryManager.java
> +    public void addTaskToHistory(Task task) {
назови просто 
add
Когда ты будешь вызывать historyManager.add() и так понятно что и куда добавляется

2024-09-09 06:48 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lyubavin/schedule/manager/InMemoryHistoryManager.java
> +
Проверку стоит оставить, в этом плане ничего не поменялось, попрежнему может придти null если задача была удалена
```
		if (task == null) {
			return;
		}
```

2024-09-09 16:39 UTC, Mentagia commented on src/ru/yandex/javacource/lyubavin/schedule/manager/InMemoryHistoryManager.java
> +    public void remove(int id) {
Прикольная конструкция. Возьму на заметку!

2024-09-10 06:04 UTC, YazykovMikhail approved these changes

2024-09-10 17:31 UTC, merged