Sprint 7 solution in file manager
Mentagia/java-kanban pull request #2
Opened 2024-09-24 19:14 UTC by Mentagia

Sprint 7 solution

2024-09-25 16:32 UTC, YazykovMikhail requested changes

2024-09-25 16:32 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lyubavin/schedule/manager/FileBackedTaskManager.java
> +        try (FileWriter writer = new FileWriter(pathToFile)) {
Используй буферизацию - для экономии ресурсов
		try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {

2024-09-25 16:32 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lyubavin/schedule/manager/FileBackedTaskManager.java
> +
Для перевода строк испольузуй:
				writer.newLine();
т.к символ еревода стоки в каждой операционной системе свой

2024-09-25 16:32 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lyubavin/schedule/manager/FileBackedTaskManager.java
> +                writer.write(task.toString());
не стоит использовать встроенный метод toString для бизнес задачи. Встроенный метод много где используется в самой системе, а тут ты его мешаешь с ббизнес требованиями. 
В задании говорится что нужно сделать отдельный метод toString
например может выглядеть так:
```
	public static String toString(Task task) {
		return task.getId() + "," + task.getType() + "," + task.getName() + "," + task.getStatus() + "," + task.getDescription() + "," + (task.getType().equals(TaskType.SUBTASK) ? ((Subtask) task).getEpicId() : "");
	}
```

2024-09-25 16:32 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lyubavin/schedule/manager/FileBackedTaskManager.java
> +                return new Epic(id, name, description);
А тут почему без статуса создаешь

2024-09-25 16:32 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lyubavin/schedule/task/Task.java
> +        return String.format("%d,%s,%s,%s,%s\n",(getId()), getType(),
Как уже говорил, не нужно мешать системные методы и бизнес, верни предыдущую реализацию

2024-09-25 16:32 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lyubavin/schedule/task/Task.java
> +        return String.format("%d,%s,%s,%s,%s\n",(getId()), getType(),
Касается всех

2024-09-25 16:32 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lyubavin/schedule/manager/InMemoryTaskManager.java
> +    final Map<Integer, Task> tasks = new HashMap<>();
protected

2024-09-25 16:32 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lyubavin/schedule/manager/FileBackedTaskManager.java
> +            for (Epic epic : taskManager.epics.values()) {
Он ведь сохранялся с актуальным статусом, с актуальным и считывай сразу, это можно опустить

2024-09-25 16:32 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lyubavin/schedule/manager/FileBackedTaskManager.java
> +
Нужно вернуться счетчик идентификаторов, ведь работа должна продолжиться

2024-09-26 16:17 UTC, Mentagia commented on src/ru/yandex/javacource/lyubavin/schedule/manager/FileBackedTaskManager.java
> +
Не подумал об этом
Учту !)

2024-09-26 16:20 UTC, Mentagia commented on src/ru/yandex/javacource/lyubavin/schedule/manager/FileBackedTaskManager.java
> +                return new Epic(id, name, description);
Просто подумал, что потом вставлю метод, который пройдется по эпиками и изменит статус в соответствии с сабтасками

2024-09-26 17:02 UTC, Mentagia commented on src/ru/yandex/javacource/lyubavin/schedule/manager/FileBackedTaskManager.java
> +                writer.write(task.toString());
Написал немного по другому так как лямбды еще не прошел :(

2024-09-26 17:09 UTC, Mentagia commented on src/ru/yandex/javacource/lyubavin/schedule/manager/InMemoryTaskManager.java
> +    final Map<Integer, Task> tasks = new HashMap<>();
А почему в этом случае не подойдет package-private? Или это для будущего рефакторинга?

2024-09-27 14:29 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lyubavin/schedule/manager/InMemoryTaskManager.java
> +    final Map<Integer, Task> tasks = new HashMap<>();
Если будет package-private то у всех в пакете будет доступ к полям. 
А нужно что бы было только у наследника, ведь только там по бизнесу они нужны

2024-09-27 14:35 UTC, YazykovMikhail approved these changes

2024-10-02 16:50 UTC, merged