Sprint 8 solution time and duration
Mentagia/java-kanban pull request #3
Opened 2024-10-12 23:46 UTC by Mentagia

Решение ФЗ 8 спринта

2024-10-14 07:26 UTC, YazykovMikhail requested changes

2024-10-14 07:26 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lyubavin/schedule/manager/InMemoryTaskManager.java
> +        return null;
throw new TaskValidationException("Задача пересекаются");

2024-10-14 07:26 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lyubavin/schedule/manager/InMemoryTaskManager.java
> +        return null;
Выбрасывай исключение, раз добавить нельзя пользователь об этом должен узнать, а сейчас нет никакой ошибки и как будто бы все ок. 
Сейчас приложение будет останавливаться при выбрасывании исключения, но потом когнда приложения будут крутиться на сервере, это будет одни из способов общения - в частности сообещние о проблемах

2024-10-14 07:26 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lyubavin/schedule/manager/InMemoryTaskManager.java
> +    protected Set<Task> prioritizedTasks = new TreeSet<>();
Сразу делай отсортированное множество:
	protected final Set<Task> prioritizedTasks = new TreeSet<>(Comparator.comparing(Task::getStartTime));

2024-10-14 07:26 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lyubavin/schedule/manager/InMemoryTaskManager.java
> +    public boolean validateTask(Task task) {
Или тут сделай возврщаемое значение void
и если проверка прошла ничего не выбрасывай, а если не прошла то выбрасывай исключение 
Что нибудь типо того:
`			throw new TaskValidationException("Задача пересекаются с id=" + t.getId() + " c " + existStart + " по " + existEnd);`
Что бы было прнятно с какой задачей пересечение.

2024-10-14 07:26 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lyubavin/schedule/manager/InMemoryTaskManager.java
> +    public boolean validateTask(Task task) {
Если будешь выбрасывать исключение тут, то в методах где вызывается проверка не нужно

2024-10-14 07:26 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lyubavin/schedule/manager/InMemoryTaskManager.java
> +    public boolean validateTask(Task task) {
Соответсвенно само исключение будет унаследовано от RuntimeException

2024-10-14 07:26 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lyubavin/schedule/manager/InMemoryTaskManager.java
> +    public boolean validateTask(Task task) {
```
public class TaskValidationException extends RuntimeException {
	public TaskValidationException() {
	}

	public TaskValidationException(String message) {
		super(message);
	}

	public TaskValidationException(String message, Throwable cause) {
		super(message, cause);
	}

	public TaskValidationException(Throwable cause) {
		super(cause);
	}

}
```

2024-10-14 18:20 UTC, Mentagia commented on src/ru/yandex/javacource/lyubavin/schedule/manager/InMemoryTaskManager.java
> +    protected Set<Task> prioritizedTasks = new TreeSet<>();
Скорее всего глупый вопрос будет, но я все же задам.
Я в классе Task Override-нул метод compareTo и имплементировал интерфейс Comparable. В этом случае всеж лучше делать отсортированное множество, как вы указали?
Или я не о том подумал...

2024-10-15 14:42 UTC, YazykovMikhail approved these changes

2024-10-15 17:19 UTC, merged